<a href="https://colab.research.google.com/github/Pratik1joshi/DeepLearning/blob/main/00_tensorflow_foundation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Fundamentals of tensorflow

In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

'2.18.0'

In [3]:
#Create tensors with tf.constant()
# Scalar - a number
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Check the number of dimensions of a tensor (ndim - number if dimensions)
scalar.ndim

0

In [6]:
#Create a vector-a number with direction
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#Dimension of vector
vector.ndim

1

In [8]:
#Create a matrix - 2dimentional matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
#Dimension of matrix
matrix.ndim

2

In [10]:
#Matrix with specified dataType
new_matrix = tf.constant([[10., 7.], [5., 6.], [2., 3.]], dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5.,  6.],
       [ 2.,  3.]], dtype=float16)>

In [11]:
#dimention
new_matrix.ndim

2

In [12]:
# Create a tensor - n-dimensional Array
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# Dimension
tensor.ndim

3

In [14]:
# variable tensors
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf .constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Changing changeable tensors using .assign()
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
# trying changing unchangeable tensor
unchangeable_tensor[0].assign(5)
unchangeable_tensor

### Creating random tensors
Random tensor are tensors of some random size which contain random numbers


In [25]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

### Shuffling tensor

In [29]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],[5,6],[2,3]])

# Shuffle the non_shuffled tensor
# shuffles 1st dimentions
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 5,  6]], dtype=int32)>

In [33]:
# Using seeds
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 2,  3]], dtype=int32)>