<a href="https://colab.research.google.com/github/Pratik1joshi/DeepLearning/blob/main/00_tensorflow_foundation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Fundamentals of tensorflow

In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

'2.18.0'

In [3]:
#Create tensors with tf.constant()
# Scalar - a number
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Check the number of dimensions of a tensor (ndim - number if dimensions)
scalar.ndim

0

In [6]:
#Create a vector-a number with direction
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#Dimension of vector
vector.ndim

1

In [8]:
#Create a matrix - 2dimentional matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
#Dimension of matrix
matrix.ndim

2

In [10]:
#Matrix with specified dataType
new_matrix = tf.constant([[10., 7.], [5., 6.], [2., 3.]], dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5.,  6.],
       [ 2.,  3.]], dtype=float16)>

In [11]:
#dimention
new_matrix.ndim

2

In [12]:
# Create a tensor - n-dimensional Array
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# Dimension
tensor.ndim

3

In [14]:
# variable tensors
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf .constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Changing changeable tensors using .assign()
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
# trying changing unchangeable tensor
unchangeable_tensor[0].assign(5)
unchangeable_tensor

### Creating random tensors
Random tensor are tensors of some random size which contain random numbers


In [25]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

### Shuffling tensor

In [29]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],[5,6],[2,3]])

# Shuffle the non_shuffled tensor
# shuffles 1st dimentions
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 5,  6]], dtype=int32)>

In [33]:
# Using seeds
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 2,  3]], dtype=int32)>

In [36]:
# Another example of shuffle
another_not_shuffled = tf.constant([[[1,2,3],[4,5,6]],
                                    [[10,11,12],[13,14,15]],
                                    [[19,20,21],[22,23,24]]])
another_not_shuffled

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [39]:
tf.random.shuffle(another_not_shuffled)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[19, 20, 21],
        [22, 23, 24]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]], dtype=int32)>

In [40]:
# Create a tensor of all ones
tf.ones([5,7])

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [41]:
#Create a tensor of all zeros
tf.zeros([5,7])

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### TURN NUMPY ARRAYS INTO TENSORS

the main difference between NumPy arrays and Tensorflow is that tensors can be run on GPU

In [43]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [44]:
# Numpy to tensor
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [45]:
# changing shapes
tensor_B = tf.constant(numpy_A, shape = (2,3,4))
tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Attributes from tensor

When dealing with tensors we probably want to be aware of the following attributes
- Shape
- Rank
- Axis or Dimension
- Size

In [46]:
#Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [50]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Nummber of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of the tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Nummber of dimensions (rank) 4
Shape of the tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


### Indexing tensors
Tensors can be indexed just like PythonList

In [52]:
#Get the first two elements of each list
#First how can we do in python list
one_list = [1,2,3,4]
print(one_list[:2])

# For tensor
rank_4_tensor[:2,:2,:2,:2]

[1, 2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [54]:
# Get the first element from each dimension except the last one
rank_4_tensor[:1,:1,:1,:] # We can just leave the last dimension empty([:1,:1,:1])

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [60]:
rank_4_tensor[:, -1]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [58]:
#Create a rank 2 tensor
rank_2_tensor = tf.constant([[5,7],[2,3]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [2, 3]], dtype=int32)>

In [59]:
#Get the last value of each row of our rank 2 tensor
# First lets try with list
one_list, one_list[-1]

([1, 2, 3, 4], 4)

In [62]:
#Now with tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [66]:
#Now lets add extra dimension on our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [7]],

       [[2],
        [3]]], dtype=int32)>

In [69]:
# Alternative to tf.newaxis
print(tf.expand_dims(rank_2_tensor, axis = 0)) #Expand the 1st dimension
tf.expand_dims(rank_2_tensor, axis = -1) # Expand the last dimension

tf.Tensor(
[[[5 7]
  [2 3]]], shape=(1, 2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [7]],

       [[2],
        [3]]], dtype=int32)>

### Manipulating the tensors(tensor operarion)

In [70]:
# Basic operation(+,-,*,/)

# You can add values to a tensor using addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [71]:
#The original tensor is unchaged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [72]:
#Multiplication
tensor*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

In [74]:
#Substraction
tensor-5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [75]:
#Division
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [76]:
#We can use tensor built in functions aswell
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

In [77]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [78]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix multiplication
In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors/matrix needs to fulfil if we are going to multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [80]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [81]:
#Matrix multiplication in Python using operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [83]:
# Create a tensor (3,4) tensor
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 